name: Setup environment
description: "[Test] Composite Action"

inputs:
  node-version:
    description: Node.js version
    required: true

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    # - name: package install
    #   shell: bash
    #   run: yarn

    # - name: firebase tools install
    #   shell: bash
    #   run: yarn global add firebase-tools
